### ISSUE TITLE
[Bug / Performace / Enhancement ] NullPointerException on many files

### ISSUE THREAD

**Issue by zenof** [hwding/pdf-unstamper#13]
```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.ArrayDeque.addLast(ArrayDeque.java:303)
	at java.base/java.util.ArrayDeque.add(ArrayDeque.java:494)
	at org.apache.pdfbox.pdmodel.PDPageTree$PageIterator.enqueueKids(PDPageTree.java:174)
	at org.apache.pdfbox.pdmodel.PDPageTree$PageIterator.enqueueKids(PDPageTree.java:169)
	at org.apache.pdfbox.pdmodel.PDPageTree$PageIterator.enqueueKids(PDPageTree.java:169)
	at org.apache.pdfbox.pdmodel.PDPageTree$PageIterator.<init>(PDPageTree.java:159)
	at org.apache.pdfbox.pdmodel.PDPageTree$PageIterator.<init>(PDPageTree.java:153)
	at org.apache.pdfbox.pdmodel.PDPageTree.iterator(PDPageTree.java:123)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at com.amastigote.unstamper.core.Processor.process(Processor.java:59)
	at com.amastigote.unstamper.util.TaskRunner.submitToProcessor(TaskRunner.java:53)
	at com.amastigote.unstamper.util.TaskRunner.procSingleFile(TaskRunner.java:44)
	at com.amastigote.unstamper.Main.main(Main.java:54)
```

**Comment by zenof** [comment]
Update: after update org.apache.pdfbox to 2.0.20, it has been fixed
